### ISSUE TITLE
Sketch of my idea... [Redis, Bungeecord and AuthMe]

### ISSUE THREAD

**Issue by sgdc3** [Xephi/AuthMeBungee#3]
Sorry if it's a bit complicated and poorly defined but it is only a sketch:

Redis Integration for AuthMe: a more stable and secure authentication system for all the large bungeecord networks.

Feel free to add all the information and ideas that you want! ;)

P.S: drawings done with http://draw.io/

![myidea 1](https://cloud.githubusercontent.com/assets/8779252/8464461/9d39d258-2042-11e5-930b-f9862455512e.png)

**Comment by sgdc3** [comment]
@Xephi what do you think about this?

**Comment by Xephi** [comment]
Need to implement Redis in AuthMe :)
